server {
    listen 80;
    listen [::]:80;
    server_name beautymaster.guru www.beautymaster.guru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name beautymaster.guru www.beautymaster.guru;

    ssl_certificate     /etc/letsencrypt/live/beautymaster.guru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/beautymaster.guru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 20M;

    location /uploads/ {
        alias /var/www/beautymaster/public/uploads/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
